name: build

on: [push, pull_request]

jobs:
    linux:
        runs-on: ubuntu-20.04
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            - name: Setup flutter
              uses: subosito/flutter-action@v2.16.0
              with:
                channel: stable
                flutter-version: 3.19.5
            - name: Get packages
              run: flutter pub get
            - name: Setup linux environment
              run: sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev
            - name: Test
              run: flutter test
            - name: Build
              run: flutter build linux --release