name: build

on: [push, pull_request]

jobs:
    linux:
        runs-on: ubuntu-20.04
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            - name: Setup Flutter
              uses: subosito/flutter-action@v2.16.0
              with:
                channel: stable
                flutter-version: latest
            - run: flutter pub get
            - run: flutter test
            - run: flutter build linux --release